/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainscreen;

import model.MarchMadnessDB;
import model.prizes.PrizeType;

/**
 *
 * @author claymackenthun
 */
public class InfoFrame extends javax.swing.JFrame {

    /**
     * Creates new form InfoFrame
     */
    public InfoFrame(MarchMadnessDB db) {
        this.db = db;
        initComponents();
        fillInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InfoTitle = new javax.swing.JLabel();
        InfoBodyScrollPane = new javax.swing.JScrollPane();
        InfoBody = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Info");
        setLocation(new java.awt.Point(350, 100));
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));

        InfoTitle.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        InfoTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InfoTitle.setText("March Madness Betting Game Info");
        InfoTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        InfoBody.setEditable(false);
        InfoBody.setBackground(new java.awt.Color(238, 238, 250));
        InfoBody.setColumns(20);
        InfoBody.setLineWrap(true);
        InfoBody.setRows(5);
        InfoBody.setTabSize(4);
        InfoBody.setWrapStyleWord(true);
        InfoBodyScrollPane.setViewportView(InfoBody);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(InfoBodyScrollPane)
                    .addComponent(InfoTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InfoTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InfoBodyScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillInfo() {
        String info = "";
        
        String overview = "OVERVIEW:\n-----------\n"
                + "\tThe March Madness Betting Game is a game that focuses"
                + " around the the NCAA Tournament. The main object is to own a "
                + "team that makes it the furthest in the bracket.\n All of the ways to "
                + "win are listed below. \n\tOnce all 64 spots have "
                + "been purchased and all 64 teams have been entered, teams can be "
                + "assigned. Once teams are assigned and scores are entered, all prize "
                + "winners will be determined and balances will be updated accordingly. "
                + "Prize winners are subject to change as scores are entered so balances "
                + "are not final until all scores have been entered.\n";
        
        String prizes = "PRIZES:\n------\n";
        for(PrizeType prize: PrizeType.values()) {
            prizes += "Prize: "+prize.getName()+" | $"+String.format("%.2f", db.getPrizeMoney(prize))+"\n";
            prizes += "Description: "+prize.getDescription()+"\n";
            prizes += "Tiebreaker: "+prize.getTiebreaker()+"\n\n";
        }
        info+=overview+"\n"+prizes;
        InfoBody.setText(info);
        InfoBody.setCaretPosition(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoFrame(null).setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea InfoBody;
    private javax.swing.JScrollPane InfoBodyScrollPane;
    private javax.swing.JLabel InfoTitle;
    // End of variables declaration//GEN-END:variables
    private MarchMadnessDB db;
}
